server:
  port: 3000
#^^^how you configure port

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: Dakota
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


#spring:
#  main:
#    web-application-type: servlet
#^^^How you turn off the webserver this would be ideal if you were making an application that didn't require one


#This is where you can configure the web server